### ISSUE TITLE
how can i predict for own pictures

### ISSUE THREAD

**Issue by hongsiyu** [SHI-Labs/Rethinking-Text-Segmentation#16]
could you provide the predtion script?

**Comment by visonpon** [comment]
Hi, I have done some modifies base on the author's scripts and test successfully on my own image. anyone who also wants to test on your own images can do as follows:
1. modify the textseg in ds_textseg.py and only use the image and correspondence gt,. just remove the bbox and so on;
2.  set the cfg.TEST.OUTPUT_RESULT to true to save the result.

**Comment by hongsiyu** [comment]
Thank you :)

**Comment by dkagramanyan** [comment]
> 

Could you please describe step by step how to run model on image to get prediction? I searched everywhere, but I didn't find any guide to lunch model not for eval or train

**Comment by dkagramanyan** [comment]
> Hi, I have done some modifies base on the author's scripts and test successfully on my own image. anyone who also wants to test on your own images can do as follows:
> 
> 1. modify the textseg in ds_textseg.py and only use the image and correspondence gt,. just remove the bbox and so on;
> 2. set the cfg.TEST.OUTPUT_RESULT to true to save the result.

Could you please describe step by step how to run model on image to get prediction? I searched everywhere, but I didn't find any guide to lunch model not for eval or train. It seems, that I don have enough skills or  your solution do not fully describe how to solve issue :).

**Comment by gwm0415** [comment]
Did you solve the problem?

**Comment by dkagramanyan** [comment]
> Did you solve the problem?

Hi!

**Comment by dkagramanyan** [comment]
> Did you solve the problem?

Hi!

No, it seems to be that this model is too complicated to make inference. I think there is way to use this model in common tasks, but you need to review all code and refactor it

**Comment by gwm0415** [comment]
> Hi, I have done some modifies base on the author's scripts and test successfully on my own image. anyone who also wants to test on your own images can do as follows:
> 
> 1. modify the textseg in ds_textseg.py and only use the image and correspondence gt,. just remove the bbox and so on;
> 2. set the cfg.TEST.OUTPUT_RESULT to true to save the result.

How to modify the modify ds_textseg.py? Could you please describe it more detailedly?
Thank you!

**Comment by gwm0415** [comment]
> > Did you solve the problem?
> 
> Hi!
> 
> No, it seems to be that this model is too complicated to make inference. I think there is way to use this model in common tasks, but you need to review all code and refactor it

Thank you for your reply！

**Comment by gwm0415** [comment]
> Hi, I have done some modifies base on the author's scripts and test successfully on my own image. anyone who also wants to test on your own images can do as follows:
> 
> 1. modify the textseg in ds_textseg.py and only use the image and correspondence gt,. just remove the bbox and so on;
> 2. set the cfg.TEST.OUTPUT_RESULT to true to save the result.

What does gt mean?

**Comment by visonpon** [comment]
![468982668](https://user-images.githubusercontent.com/11517731/155501643-414a29f4-5b25-4201-9ca4-6e6660bec918.jpg)
Hope this can help you.
in face you can follow the errors you encountered and try to simple to code as you need, for train on your own datasets, you can also  based on the scripts provided.

**Comment by karanthacker** [comment]
Hi @visonpon  were you able to remove the gpu dependency of the script

**Comment by xingqian2018** [comment]
The repo now includes a simple script: `inference.py` for predicting your own images. Thanks for your interest in the work! Let me know if this works :P.
