### ISSUE TITLE
how do you create the mask picture

### ISSUE THREAD

**Issue by Patriciayufish** [SHI-Labs/Rethinking-Text-Segmentation#17]
Could you please teach me how to create the mask picture? I want to use my own dataset, but it doesn't contain gt pictures for segmentation, so I want to create one myself. I tried to convert the picture simply by using convert('L'), but the result is not so satisfying, could you please public the way to create the masks?

**Comment by xingqian2018** [comment]
Hi, not sure we get you correctly. We manually label these masks. If you mean to convert the charater-level masks to word-level masks, you shouldn't need to do that because we provide word-level masks in the dataset.
