### ISSUE TITLE
TextSeg Dataset Question

### ISSUE THREAD

**Issue by heping0307** [SHI-Labs/Rethinking-Text-Segmentation#19]
Does anyone share the data？I sent the above email “textseg.dataset@gmail.com”, but it didn't reply to me.
If you can，please send it to my email “ping.he@nlpr.ia.ac.cn”  Thank you！

**Comment by xingqian2018** [comment]
Hi Ping, I just ask the team. Looks like they have sent you the dataset 3 days ago. Please send another email if you didn't get it.

**Comment by heping0307** [comment]
I have received it. Thank you very much！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SHI-Labs/Rethinking-Text-Segmentation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月2日(星期六) 上午7:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SHI-Labs/Rethinking-Text-Segmentation] TextSeg Dataset Question (#19)





 
Hi Ping, I just ask the team. Looks like they have sent you the dataset 3 days ago. Please send another email if you didn't get it.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
