### ISSUE TITLE
How you annotated the text?

### ISSUE THREAD

**Issue by zobeirraisi** [SHI-Labs/Rethinking-Text-Segmentation#2]
Thanks for the amazing work; I saw your segmentation annotation for characters with different styles. Could you please let me know how you have annotated all the text in your dataset?

**Comment by xingqian2018** [comment]
Thanks for your interest in our work. All annotations are human-labeled. Text with styles can be masked into "text" (main surface of the text) & "text-effect" (3d effect, halos, shadows, decorations, ...), in which those "text" masks are further split into character-wise masks. Hope this answers your question.

**Comment by xingqian2018** [comment]
> Thanks for the amazing work; I saw your segmentation annotation for characters with different styles. Could you please let me know how you have annotated all the text in your dataset?

Thanks for your interest in our work. All annotations are human-labeled. Text with styles can be masked into "text" (main surface of the text) & "text-effect" (3d effect, halos, shadows, decorations, ...), in which those "text" masks are further split into character-wise masks. Hope this answers your question.
