### ISSUE TITLE
result on COCO_TS and MLT_S dataset

### ISSUE THREAD

**Issue by vince2003** [SHI-Labs/Rethinking-Text-Segmentation#21]
Dear Authors,
Thank you for your great work. However, I don't understand how you visualize and calculate metrics for COCO_TS and MLT_S datasets. Specifically, in Figures 5.c and 5.d, the original ground-truth of COO_TS and MLT_S datasets have very low quality. They look like the disconnected boundary of text rather than pixel-level ground truth for segmentation. 
![img_1006](https://user-images.githubusercontent.com/39032947/143886136-28f1b55b-bd4d-49a1-b0e6-1119c002a2de.png)

Question1: How to preprocess this original ground-truth to have visualization as Figure 5.c and 5.d?
Question2: For the result of the COCO_TS and MLT_S dataset in Table 2, do you use original ground truth directly or processed ground truth for training? How to preprocess this original ground truth?
I'm looking forward to hearing from you.
Thank you!

**Comment by xingqian2018** [comment]
a) For COCO_TS and MLT_S, the dataset provides three labels, bg / fg / ignore, so figure 5c and 5d is just a plot of bg->black fg->red and ignore->white.
b) I use the ground truth (bg / fg / ignore) for training. No preprocessing.
