### ISSUE TITLE
Error predicting using pretrained model

### ISSUE THREAD

**Issue by ManuBN786** [SHI-Labs/Rethinking-Text-Segmentation#22]
FileNotFoundError: [Errno 2] No such file or directory: /Rethinking-Text-Segmentation/data/TextSeg/split.json'

How to predict using pretrained model ?

**Comment by xingqian2018** [comment]
In the google drive link sent through email, there is a split.json

**Comment by an2416** [comment]
@xingqian2018 
I'm also suffer same issue.
Could you share split.json file for me ?
