### ISSUE TITLE
which training dataset used for testing ICDAR13 FST and Total-Text dataset?

### ISSUE THREAD

**Issue by vince2003** [SHI-Labs/Rethinking-Text-Segmentation#23]
Dear Authors,
Thank you for your great work. I have one question:
The number of images in ICDAR13 FST and Total-Text is too small (462 and 1555 images). Which is their training dataset ? (corresponding to in table 2 of your paper)
Thank you!

**Comment by xingqian2018** [comment]
For ICDAR I think the default setting is 229 in train and 233 in val, so we do the same. 
For Total-Text, the default is 1255 in train and 300 in val, we follow that as well.
