### ISSUE TITLE
Dataset request 

### ISSUE THREAD

**Issue by hiyaroy12** [SHI-Labs/Rethinking-Text-Segmentation#29]
Hi, I have sent email to “[textseg.dataset@gmail.com](mailto:textseg.dataset@gmail.com)” requesting the TextSeg dataset for research purposes. If you can, please send it to my email “[hiyaroy12@gmail.com](mailto:hiyaroy12@gmail.com)” Thank you！

**Comment by xingqian2018** [comment]
I just contacted the email guy, I think he had already sent u the link. Sorry for the delay.
