### ISSUE TITLE
Will you share the training and evaluation code?

### ISSUE THREAD

**Issue by mahiratmis** [SHI-Labs/Rethinking-Text-Segmentation#3]

**Comment by ishaybeyondminds** [comment]
please share when you update your code

**Comment by xingqian2018** [comment]
> _No description provided._



> please share when you update your code

Hi, thanks for your interest in our work. The code will be posted soon. (After ICCV ddl)

**Comment by chriscpy** [comment]
when will the code be available?

**Comment by xingqian2018** [comment]
> when will the code be available?

Hi, the code is now on the github.
