### ISSUE TITLE
Dataset Requests

### ISSUE THREAD

**Issue by Mountchicken** [SHI-Labs/Rethinking-Text-Segmentation#32]
Hi guys, 
     Thanks for your great work! I just sent an email to apply for TextSeg dataset. My email is mountchicken@qq.com, and hope to get your reponse soon. Many thanks❤

**Comment by TongkunGuan** [comment]
Hi! I have read your paper and connected to you by email. And I will use your dataset for academics.
please check the email as soon as possible. Thanks!

**Comment by Mountchicken** [comment]
Just received.
